# Generated by Django 6.0.3 on 2026-03-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('is_test_active', models.BooleanField(default=False, help_text='Switch this to True on event day to reveal the test link to users.')),
                ('test_link', models.URLField(blank=True, help_text='Link to the test form/page', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('is_revealed', models.BooleanField(default=False, help_text='Switch this to True to display this speaker on the frontend.')),
            ],
        ),
    ]
