# Generated by Django 6.0.3 on 2026-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_sheet_link', models.URLField(blank=True, max_length=500)),
                ('main_sheet_name', models.CharField(default='Sheet1', max_length=100)),
                ('col_name', models.CharField(default='Name', help_text="Header name for the student's name", max_length=50)),
                ('col_email', models.CharField(default='Email ID', help_text="Header name for the student's email", max_length=50)),
                ('col_ticket_status', models.CharField(default='Ticket Status', max_length=50)),
                ('col_email_status', models.CharField(default='Email Status', max_length=50)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_app_password', models.CharField(blank=True, help_text='App password for Gmail', max_length=255)),
                ('ticket_template_url', models.URLField(blank=True, max_length=500)),
                ('email_message_url', models.URLField(blank=True, max_length=500)),
                ('font_url', models.URLField(blank=True, max_length=500)),
                ('name_text_x_pos', models.IntegerField(default=1823)),
                ('name_text_y_pos', models.IntegerField(default=299)),
                ('qr_code_x_pos', models.IntegerField(default=1610)),
                ('qr_code_y_pos', models.IntegerField(default=343)),
                ('font_size', models.IntegerField(default=147)),
                ('qr_code_target_size', models.IntegerField(default=260)),
                ('mongo_uri', models.CharField(blank=True, help_text='MongoDB connection string', max_length=500)),
                ('mongo_db_name', models.CharField(blank=True, max_length=100)),
                ('mongo_collection_name', models.CharField(blank=True, max_length=100)),
                ('google_service_account_json', models.TextField(blank=True, help_text='Paste the entire JSON string here')),
            ],
            options={
                'verbose_name': 'Ticketing Configuration',
                'verbose_name_plural': 'Ticketing Configuration',
            },
        ),
    ]
