# Generated by Django 6.0.3 on 2026-03-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_ticketingconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_test_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='test_link',
        ),
    ]
