# Generated by Django 6.0.3 on 2026-03-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_is_test_active_remove_event_test_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_sheet_link', models.URLField(help_text='Paste the link to the Google Sheet where answers should be saved', max_length=500)),
                ('sheet_name', models.CharField(default='Sheet1', help_text="Usually 'Sheet1' or 'Form Responses 1'", max_length=100)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The question (e.g., 'Phone Number', 'Branch')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('checkbox', 'Checkbox (Yes/No)')], default='text', max_length=20)),
                ('options', models.TextField(blank=True, help_text='If Dropdown, comma-separated options (e.g. CSE, IT, ME)')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.registrationform')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
