# Generated by Django 6.0.3 on 2026-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registrationform_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='drive_folder_link',
            field=models.URLField(blank=True, help_text="Optional: If using 'File Upload' fields, paste the Google Drive folder link to save user files.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('select', 'Dropdown'), ('checkbox', 'Checkbox (Multiple Options)'), ('file', 'File Upload (Images/PDFs)')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(help_text="The question (e.g., 'Phone Number', 'Upload ID')", max_length=200),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='If Dropdown or Checkbox, enter options separated by commas (e.g. Option 1, Option 2, Option 3)'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='is_revealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='col_email',
            field=models.CharField(default='Email ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='col_name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='google_service_account_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='mongo_uri',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='sender_app_password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
