# Generated by Django 6.0.3 on 2026-03-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_registrationform_drive_folder_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationform',
            name='drive_folder_link',
        ),
        migrations.AddField(
            model_name='ticketingconfig',
            name='cloudinary_api_key',
            field=models.CharField(blank=True, help_text='Your Cloudinary API Key', max_length=100),
        ),
        migrations.AddField(
            model_name='ticketingconfig',
            name='cloudinary_api_secret',
            field=models.CharField(blank=True, help_text='Your Cloudinary API Secret', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketingconfig',
            name='cloudinary_cloud_name',
            field=models.CharField(blank=True, help_text='Your Cloudinary Cloud Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='If Dropdown or Checkbox, enter options separated by commas (e.g. Option 1, Option 2)'),
        ),
    ]
