# Generated by Django 6.0.3 on 2026-03-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_registrationform_drive_folder_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketingconfig',
            name='auto_generate_tickets',
            field=models.BooleanField(default=False, help_text='If True, tickets are generated and emailed INSTANTLY when a user registers.'),
        ),
        migrations.AddField(
            model_name='ticketingconfig',
            name='confirmation_mail_template_url',
            field=models.URLField(blank=True, help_text="Link to the HTML email sent to say 'Your form is under review' (Used if Auto-Generate is OFF)", max_length=500),
        ),
    ]
