# Generated by Django 5.2.14 on 2026-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_ticketingconfig_auto_generate_tickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_theme_code',
            field=models.TextField(blank=True, help_text='Paste raw CSS or JSON config code here to override the frontend theme for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_theme_file',
            field=models.FileField(blank=True, help_text='Upload a custom theme file (CSS or JSON) for this event.', null=True, upload_to='event_themes/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark True when the event is over to move it to past events and revert frontend styling.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketingconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
