# Generated by Django 6.0.3 on 2026-03-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customuser',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Under Review'), ('approved', 'Approved / Ticket Generated'), ('rejected', 'Rejected / Full')], default='pending', max_length=20),
        ),
    ]
